IF (NOT EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES WHERE
                 TABLE_SCHEMA = 'dbo' AND  
				 TABLE_NAME = '{0}'))
BEGIN
    CREATE TABLE {0} ( 
		[SCRIPT_NAME] [NVARCHAR](200) NOT NULL, 
		[APPLY_DATE] [DATETIME] NOT NULL
	)
END
